import path from 'path'
import { fileURLToPath } from 'url'
import AutoLoad from '@fastify/autoload'
import scalarApiReference from '@scalar/fastify-api-reference'
import cookie from '@fastify/cookie'
import type { FastifyInstance, FastifyPluginOptions } from 'fastify'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Pass --options via CLI arguments in command to enable these options.
const options = {}

export default async function (fastify: FastifyInstance, opts: FastifyPluginOptions) {
  // Place here your custom code!

  // Register cookie plugin globally
  await fastify.register(cookie)

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  await fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins'),
    options: Object.assign({}, opts)
  })

  // This loads all modules defined in modules directory
  await fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'modules'),
    maxDepth: 1,
    dirNameRoutePrefix: false,
    matchFilter: (path: string) => path.endsWith('.module.ts'),
    options: Object.assign({}, opts)
  })

  // Register Scalar API reference after routes are loaded
  // It will use the OpenAPI schema generated by @fastify/swagger
  await fastify.register(scalarApiReference, {
    routePrefix: '/reference',
    configuration: {
      spec: {
        content: async () => {
          // Get the OpenAPI schema from Fastify Swagger
          return fastify.swagger()
        }
      }
    }
  })
}

export { options }

